package com.oms.notification.entity;

public enum NotificationType {
    ORDER_CONFIRMATION,
    ORDER_STATUS_UPDATE,
    ORDER_CANCELLATION,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    PAYMENT_CONFIRMATION,
    SYSTEM_NOTIFICATION,
    PROMOTIONAL
}