server:
  port: 8081

spring:
  application:
    name: auth-service

  # H2 Database configuration for testing
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: auth123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTBBQkNERUY=
  expiration: 86400000 # 24 hours in milliseconds
