server:
  port: 8083

spring:
  application:
    name: notification-service

  # H2 Database configuration for testing
  datasource:
    url: jdbc:postgresql://localhost:5435/notificationdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ${NOTIFICATION_DB_PASSWORD:notification123}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Kafka Configuration - Simplified
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group-v5
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

jwt:
  secret: ${JWT_SECRET:bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTBBQkNERUY=}
  expiration: 86400000 # 24 hours in milliseconds

# Enable Kafka
kafka:
  enabled: true
  topics:
    order-events: order-events

# Email settings
email:
  enabled: false # Set to true when you want to send actual emails
  from: noreply@oms.com
