server:
  port: 8082

spring:
  application:
    name: order-service

  # H2 Database configuration for testing
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # Enable H2 console for debugging
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      adjust-dates-to-context-time-zone: false

jwt:
  secret: bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTBBQkNERUY=
  expiration: 86400000 # 24 hours in milliseconds

auth:
  service:
    url: http://localhost:8081 # Auth service URL

# Enable Kafka
kafka:
  enabled: true
  topics:
    order-events: order-events-v2
