server:
  port: 8082

spring:
  application:
    name: order-service

  # PostgreSQL Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5434/orderdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ${ORDER_DB_PASSWORD:order123}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      adjust-dates-to-context-time-zone: false

jwt:
  secret: ${JWT_SECRET:bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTBBQkNERUY=}
  expiration: 86400000 # 24 hours in milliseconds

auth:
  service:
    url: http://localhost:8081 # Auth service URL

# Enable Kafka
kafka:
  enabled: true
  topics:
    order-events: order-events
